Repository bbc/sqs-consumer, pull requests merged in 2022-04, with the labels that each got.

#282 Bump debug from 4.1.1 to 4.3.1
  package-lock.json
  package.json
Labels: dependencies, simple fix

#274 Fix documented required IAM actions
  README.md
Labels: Documentation, simple fix

#246 Included https module on example
  README.md
Labels: Documentation, simple fix

#287 Option to not don't delete messages from sqs
  README.md
  src/consumer.ts
  test/consumer.ts
Labels: simple fix

#286 Update README.md - Fix sentence mismatch message is also included in params and not error
  README.md
Labels: simple fix
